### ISSUE TITLE
Using nordpool as a backup dosn't seem to work

### ISSUE THREAD

**Issue by SVH-Powel** [jpulakka/nordpool_diff#23]
![image](https://user-images.githubusercontent.com/64255194/199024768-1d8bd256-8677-4de2-b09e-adc56ff8e31f.png)

2022-10-31 14:48:39.622 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.nordpool_diff_rank_10_normalize_max_min fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in async_device_update
raise exc
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/nordpool_diff/sensor.py", line 139, in update
prices = self._get_next_n_hours(self._filter_length + 1) # +1 to calculate next hour
File "/config/custom_components/nordpool_diff/sensor.py", line 148, in _get_next_n_hours
prices = _get_next_n_hours_from_entsoe(n, e)
File "/config/custom_components/nordpool_diff/sensor.py", line 83, in _get_next_n_hours_from_entsoe
if p := e.attributes["prices"]:
KeyError: 'prices'

![image](https://user-images.githubusercontent.com/64255194/199025054-fb3f8aa4-288f-4f15-8ad0-c5be0a590e42.png)

**Comment by jpulakka** [comment]
@SVH-Powel Can you try tip of master, if it works for you? I don't have access to my hass right now..

**Comment by stigvi** [comment]
No worries. This lastet for a few minutes and I wasn't able to test anything. But I can test it later, maybe tomorrow

**Comment by jpulakka** [comment]
Yep, so indeed the fallback didn't work if entsoe sensor was missing the whole "prices" attribute.

That is now fixed, error handling is much more robust. I'll release 0.2.1 with this soon.
